In [1]:
import numpy as np

a = rand_matrix = np.random.randint(1, 50, size=(5, 4))
print(a)


[[ 9  5 10 39]
 [ 1 46 21 30]
 [42 18  4 20]
 [38 19 32 47]
 [17 45 35 20]]


In [5]:
rows, cols = a.shape
i = 0
j = cols - 1
while i < rows and j >= 0:
    print(a[i][j])
    i += 1
    j -= 1

39
21
18
38


In [3]:
print(np.max(a[0, :]))
print(np.max(a[1, :]))
print(np.max(a[2, :]))
print(np.max(a[3, :]))
print(np.max(a[4, :]))

39
46
42
47
45


In [6]:
mean = np.mean(a)
b = a[a > mean]

print(mean)
print(b)

24.9
[39 46 30 42 38 32 47 45 35]


In [11]:
import numpy as np

def numpy_boundary_transversal(arr):
    a = 0
    b = 0
    spiral = []

    rows, cols = arr.shape

    for b in range(0, cols):
     spiral.append(int(arr[a][b]))

    for a in range(1, rows):
     spiral.append(int(arr[a][b]))

    if rows - 1 > 0:
     for b in range(cols - 2 , - 1, -1):
      spiral.append(int(arr[a][b]))

    if cols - 1 > 0:
     for a in range(rows - 2 , 0, -1):
      spiral.append(int(arr[a][b]))


    return spiral

print(numpy_boundary_transversal(a))


[9, 5, 10, 39, 30, 20, 47, 20, 35, 45, 17, 38, 42, 1]
